### PR TITLE
stylesheet attributes

### PR DESCRIPTION
**Pull request by opoudjis**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@opoudjis is this a normal CSS override or an SCSS override? We don’t include the sass gem in runtime.

**Comment by opoudjis** [comment]
you're right, it is meant to be css override. (In fact I do run those overrides through the sassc engine, because I run everything through them, but I am aware of that issue. Will reword.)

**Comment by ronaldtse** [comment]
> In fact I do run those overrides through the sassc engine, because I run everything through them

@opoudjis this statement is strange -- we do not have sassc installed on user computers, only for developers. Remember there is no Sass in the released Metanorma gems?

**Comment by opoudjis** [comment]
I was wrong, the override stylesheets are in fact just passed through, and not preprocessed as SCSS.

**Comment by ronaldtse** [comment]
Thank you @opoudjis for confirming!

**Pull request merged**
