### PR TITLE
Blog post on relaton-doi

### PR DESCRIPTION
**Pull request by opoudjis**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by opoudjis** [comment]
This is a new blog post announcing relaton-doi

It CANNOT be published until the following tickets are finalised:

* https://github.com/relaton/relaton-doi/issues/10
* https://github.com/relaton/relaton-doi/issues/12
* https://github.com/metanorma/metanorma-standoc/issues/726

@andrew2net Please review, and add to it anything you think useful, especially for use of relaton-doi by people outside of Metanorma (e.g. export to other database formats.)

**Review by andrew2net — APPROVED** [review]

**Comment by andrew2net** [comment]
@opoudjis sorry I merged the PR by mistake. Should I revert it?

**Comment by ronaldtse** [comment]
@andrew2net yes please revert it, thanks.

**Comment by andrew2net** [comment]
@opoudjis @ronaldtse recreated this PR here https://github.com/metanorma/metanorma.org/pull/700

**Pull request merged**
