### PR TITLE
metanorma/metanorma-docker#119 replace references to *.scss with *.css

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma-docker#119

### Metanorma PR checklist

 - NO Breaking changes (list related PRs)
 - NO Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - NO External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - NO Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP There are two issues to resolve:

1. Can people use SASS or only CSS?
2. Add instructions on how to build your own Docker container with a custom flavor.

**Comment by CAMOBAP** [comment]
> 1. Can people use SASS or only CSS?

As far as I understand it depends:
 - for packed-mn-based solutions it's impossible. for Docker and Ruby it's possible if `sassc` installed

@ronaldtse @strogonoff @opoudjis  Could you please suggest a good page to add this information?

> 2. Add instructions on how to build your own Docker container with a custom flavor.

@ronaldtse  Any suggestion which Dockerfile should be used as base?

**Comment by ronaldtse** [comment]
1. Yes, only docker based solutions can use SASS. We need to make that clear. I think we need a guide for a flavor builder. We don't have a good guide right now. 
2. Probably metanorma/metanorma?

**Review by opoudjis — APPROVED** [review]

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
The reason I didn't merge this a while ago is that we need better quality docs for Metanorma adoption. Will create a new ticket for that.

**Pull request merged**
