### PR TITLE
ISO sections, keeptitle attribute: https://github.com/metanorma/metan…

### PR DESCRIPTION
**Pull request by opoudjis**
…orma-iso/issues/1124

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
Pending @Intelligent2013 clarification on what `narrow` and `text-width` attributes differ.

**Comment by Intelligent2013** [comment]
These figure's width values were introduced specially for BSI documents: https://github.com/metanorma/metanorma-bsi/issues/276, because the BSI Style guide for British Standards determine them:
image

But there isn't any 'narrow' figure example.

As I noted a year ago https://github.com/metanorma/mn-samples-bsi/issues/171#issuecomment-1435700053
> For `narrow` option we don't have the sample.

Therefore, currently in the XSLT for PDF there isn't any processing for the `width="narrow"`, because we don't know how to scale the figure with `narrow` value.
I.e. currently, metanorma allows the value `narrow`, but PDF XSLT doesn't use it.

**Comment by opoudjis** [comment]
https://www.overleaf.com/learn/latex/Lengths_in_LaTeX, https://en.wikibooks.org/wiki/LaTeX/Lengths does not answer the question of what "narrow" means, but it does give us a set of possible values for widths that reference text:

* \columnwidth
* \linewidth "Width of the line in the current environment."
* \paperwidth (= full-page-width)
* \textwidth "Width of the text area in the page"

My strong suspicion is that narrow is not defined, and is merely "not full textwidth or paperwidth"; but nobody wants to commit to a fixed answer in 

* https://tex.stackexchange.com/questions/158685/ideal-width-of-figures-compared-to-the-text-width
* https://tex.stackexchange.com/questions/5351/typographic-conventions-for-width-of-figures-in-latex-data-analysis-reports

For instance.

> The width of your figures will be very much dependent of the layout you use. As `@Christian`, I would actually try not to divert from the rule that figure width = \textwidth. With small figures, you could go for a half or a third of that width and put them in the same float. With very large figures, dedicate a page to the whole thing and set it to 100% of the height or width (whichever is bigger). If you are using a layout such as tufte-latex, get the small figures into the margins and it will look gorgeous all the same. Just be consistent with yourself.

So user ienissei defaults to textwidth, allows 1/2 or 1/3 textwidth for small images; I imagine that BSI intend narrow to include '1/2 or 1/3 textwidth", without fixing it.

image

These instances of images shoved into margins would also count as margins, but that's a bit old-fashioned for standards:

image


... If my interpretation is correct, it means that "narrow" is meaningless as an option describing figure width, it is merely a vague description, and users should actually specify something more concrete. Even if it isn't, I think we might as well drop it.

Having looked at LaTeX, I now think that we should not be reinventing its width notation. If LaTeX allows "width=.5\textwidth", why don't we just use LaTeX notation for this field?

**Comment by opoudjis** [comment]
So @ronaldtse @Intelligent2013 the actions coming out of this discussion are:

* Either  confirm with BSI if "narrow" is a well-defined table and figure width, and if so, how to render it
* Or, drop support for "narrow", because "narrow" is merely an open-ended, "not full width" value --- which in our documents should be replaced by either no width indication, or else an explicit width indication. (That is my preference.)

There is a further question of whether we should be supporting fractions relative to textwidth and pagewidth, as LaTeX does. The thing is, that requirement comes out of only LaTeX and/or PDF. Nobody in HTML thinks in those terms: percentages are relative to div containers or text width, the page/text distinction does not apply. Nobody in Word thinks in those terms: table widths are more simply encoded as absolute  values.

So if there is a requirement for supporting fractions relative to textwidth and pagewidth, it only applies to @Intelligent2013, and I presume it also needs to come from @Intelligent2013 and his experience generating PDFs in response to SDOs.

My suspicion is, if we haven't implemented anything like it already, we won't need to, and that 1/2 or 1/3 width images are unfashionable anyway. There is a reason why we have no idea from BSI what narrow width looks like, after all: that they're simply not using it.

Over to you guys.

**Comment by ronaldtse** [comment]
Then let's drop `narrow` until it comes back. Thanks

**Pull request merged**
