### PR TITLE
Doc20220602

### PR DESCRIPTION
**Pull request by opoudjis**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by opoudjis** [comment]
@strogonoff Needs your review as to why the newly added pages under _pages/install are not indenting properly

**Comment by strogonoff** [comment]
> @strogonoff Needs your review as to why the newly added pages under _pages/install are not indenting properly

Not sure what the question is here

**Comment by strogonoff** [comment]
This can be addressed by following frontmatter convention of sibling pages.

**Comment by opoudjis** [comment]
> This can be addressed by following frontmatter convention of sibling pages.

... ?

**Pull request merged**
