### PR TITLE
actions-mn/cli#6 add documentation for actions-mn

### PR DESCRIPTION
**Pull request by CAMOBAP**
- actions-mn/cli#6

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse if there is no objections I propose to merge this one

**Comment by opoudjis** [comment]
@CAMOBAP Ronald likely already told you this, but he has not merged anything since November, because he has been working on refactoring it ever since. Therefore, no PRs here have been merged.

@ronaldtse swore to me 10 days ago that he would get this done some time this month.

Month is almost up.

**Comment by CAMOBAP** [comment]
@opoudjis who can I ask for review this, or it's ok to merge on my own?

**Comment by opoudjis** [comment]
> @opoudjis who can I ask for review this, or it's ok to merge on my own?

It is emphatically not OK to merge on your own, because Ronald has an open refactor. (As he has had for the past 10 months.)  

The reviewer on metanoma.org is only Ronald. Until anyone says otherwise, you must never merge metanorma.org updates on your own.

Yes. I know.

**Comment by opoudjis** [comment]
@CAMOBAP Given the continuing inaction from @ronaldtse I am unilaterally merging this pending PR into doc20230606, which has been my working PR since June.

**Pull request closed without merging**
