### PR TITLE
concept refactor: https://github.com/metanorma/metanorma-standoc/issu…

### PR DESCRIPTION
**Pull request by opoudjis**
…es/491

### CODE REVIEW

**Comment by opoudjis** [comment]
Could not make serve locally:

````
bundler: failed to load command: jekyll (/Users/nickn/.rvm/gems/ruby-2.7.2/bin/jekyll)
RuntimeError: Navigation item matching GbDoc_GbStandardPrefix.png (specs/metanorma-model-gb) was not found
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/spec_builders/png_diagrams.rb:72:in `block in build_spec_pages'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/spec_builders/png_diagrams.rb:57:in `glob'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/spec_builders/png_diagrams.rb:57:in `build_spec_pages'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/spec_builders/spec_builder.rb:23:in `build'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/project_data_reader.rb:162:in `build_and_read_spec_pages'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/project_data_reader.rb:196:in `block in fetch_and_read_specs'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/project_data_reader.rb:194:in `each'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/project_data_reader.rb:194:in `fetch_and_read_specs'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-theme-open-project-helpers-2.1.7/lib/jekyll-theme-open-project-helpers/project_data_reader.rb:88:in `read'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/site.rb:180:in `read'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/site.rb:78:in `process'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
  /Users/nickn/.rvm/gems/ruby-2.7.2/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
  /Users/nickn/.rvm/gems/ruby-2.7.2/bin/jekyll:23:in `load'
  /Users/nickn/.rvm/gems/ruby-2.7.2/bin/jekyll:23:in `<top (required)>'
make: *** [serve] Error 1
````

metanorma-gb has not been maintained for months, and mentioning it here, let alone making updating its modelling a dependency for the site, is counterproductive.

**Comment by ronaldtse** [comment]
@opoudjis this is due to some uncleared cache in your repo, please re-clone it. This issue has been fixed some time ago.

**Comment by ronaldtse** [comment]
BTW, the main branch is now `main`.

**Comment by ronaldtse** [comment]
@opoudjis updated for your review.

**Pull request merged**
