### PR TITLE
Blog post on relaton-doi

### PR DESCRIPTION
**Pull request by andrew2net**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by andrew2net** [comment]
This is a new blog post announcing relaton-doi

It CANNOT be published until the following tickets are finalised:

* https://github.com/relaton/relaton-doi/issues/10
* https://github.com/relaton/relaton-doi/issues/12
* https://github.com/metanorma/metanorma-standoc/issues/726

@andrew2net Please review, and add to it anything you think useful, especially for use of relaton-doi by people outside of Metanorma (e.g. export to other database formats.)

**Review by opoudjis — APPROVED** [review]
OK, but can't go live until relaton-doi release

**Comment by opoudjis** [comment]
Free to be published now.

**Comment by ronaldtse** [comment]
I'm moving Relaton content for https://github.com/relaton/relaton.github.io/issues/61
* PR: https://github.com/relaton/relaton.github.io/pull/62

I will keep Metanorma specific content here.

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
